// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc_Pet_App_StoredProcedure.Models;

#nullable disable

namespace Mvc_Pet_App_StoredProcedure.Migrations
{
    [DbContext(typeof(PetAppDbContext))]
    [Migration("20240525055917_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mvc_Pet_App_StoredProcedure.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<int?>("Category")
                        .HasColumnType("int")
                        .HasColumnName("category");

                    b.Property<string>("Location")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__pet__3213E83FC83985CB");

                    b.HasIndex("Category");

                    b.ToTable("pet", (string)null);
                });

            modelBuilder.Entity("Mvc_Pet_App_StoredProcedure.Models.PetCategory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__PetCateg__3213E83F3A8F1160");

                    b.ToTable("PetCategory", (string)null);
                });

            modelBuilder.Entity("Mvc_Pet_App_StoredProcedure.Models.Pet", b =>
                {
                    b.HasOne("Mvc_Pet_App_StoredProcedure.Models.PetCategory", "CategoryNavigation")
                        .WithMany("Pets")
                        .HasForeignKey("Category")
                        .HasConstraintName("FK__pet__category__45F365D3");

                    b.Navigation("CategoryNavigation");
                });

            modelBuilder.Entity("Mvc_Pet_App_StoredProcedure.Models.PetCategory", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
