CREATE DATABASE HireMeNowDB
USE HireMeNowDB

CREATE TABLE Companies(
Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
Name varchar(100)NULL,
Email varchar(50) NOT NULL UNIQUE,
Website varchar(50) NULL,
Phone varchar(50) NULL,
About varchar(300) NULL,
Location varchar(50) NULL,
Status varchar(50) NULL
);
INSERT INTO Companies VALUES(NEWID(),'HANEESHA','A@GMAIL.COM','A.COM','7654326837','VFGHBDNESWDFNHVBNJNEDSDES','LONDON','ACTIVE')
INSERT INTO Companies VALUES(NEWID(),'HANE','B@GMAIL.COM','B.COM','7654326839','VFGHBDNEBHCNHVBNJNEDSDES','LONDON','ACTIVE')
INSERT INTO Companies VALUES(NEWID(),'HANEES','C@GMAIL.COM','C.COM','7654326836','VFGHBDNEBHCNHVVGBNNEDSDES','LONDON','ACTIVE')
INSERT INTO Companies VALUES(NEWID(),'HA','D@GMAIL.COM','D.COM','7654326838','VFGHBDNEBHCNHVBNJNEDRFTGHSDES','LONDON','ACTIVE')
SELECT * FROM Companies

EXEC sp_rename 'Companies','Company'
SELECT * FROM Company

ALTER TABLE Company ALTER COLUMN About varchar(300)
EXEC sp_rename 'Company.Location','Place'

SELECT * FROM Company

UPDATE Company SET Name = 'AITRICH ACADEMY' WHERE Email='A@GMAIL.COM'

DELETE FROM Company WHERE Email='Y@GMAIL.COM'


CREATE TABLE Users
(
Id UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
firstName varchar(50) NULL,
LastName varchar(50) NULL,
Email varchar(50) NULL,
Gender varchar(50) NULL,
Location varchar(50) NULL,
CompanyId uniqueidentifier NULL,
Status varchar(50) NULL
);
ALTER TABLE Users ADD CONSTRAINT email_unique UNIQUE(Email)


INSERT INTO Users values(NEWID(),'ALEXANDER','JOHN','A@GMAIL.COM','MALE','BANGALORE',NEWID(),'ACTIVE','JOBPROVIDER')
INSERT INTO Users values(NEWID(),'DR','SMITH','S@GMAIL.COM','FEMALE','DELHI',NEWID(),'INACTIVE','JOBSEEKER')
INSERT INTO Users values(NEWID(),'MARY','THOMAS','Y@GMAIL.COM','MALE','LONDON',NEWID(),'ACTIVE','Company owner')

Alter Table Users Add Roles varchar(50)


SELECT * FROM Users

UPDATE Users SET Location = 'KOCHI' WHERE Email = 'S@GMAIL.COM'

SELECT*FROM Users WHERE Roles = 'JOBSEEKER'