USE [master]
GO
/****** Object:  Database [Mvc_Pet_Db]    Script Date: 28-05-2024 11:03:27 ******/
CREATE DATABASE [Mvc_Pet_Db]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Mvc_Pet_Db', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Mvc_Pet_Db.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Mvc_Pet_Db_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Mvc_Pet_Db_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Mvc_Pet_Db] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mvc_Pet_Db].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Mvc_Pet_Db] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET ARITHABORT OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Mvc_Pet_Db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Mvc_Pet_Db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Mvc_Pet_Db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Mvc_Pet_Db] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Mvc_Pet_Db] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET RECOVERY FULL 
GO
ALTER DATABASE [Mvc_Pet_Db] SET  MULTI_USER 
GO
ALTER DATABASE [Mvc_Pet_Db] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Mvc_Pet_Db] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Mvc_Pet_Db] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Mvc_Pet_Db] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Mvc_Pet_Db] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Mvc_Pet_Db] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Mvc_Pet_Db', N'ON'
GO
ALTER DATABASE [Mvc_Pet_Db] SET QUERY_STORE = ON
GO
ALTER DATABASE [Mvc_Pet_Db] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Mvc_Pet_Db]
GO
/****** Object:  User [soudha]    Script Date: 28-05-2024 11:03:27 ******/
CREATE USER [soudha] FOR LOGIN [soudha] WITH DEFAULT_SCHEMA=[dbo]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 28-05-2024 11:03:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[pet]    Script Date: 28-05-2024 11:03:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[pet](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](50) NULL,
	[age] [int] NULL,
	[Location] [varchar](50) NULL,
	[category] [int] NULL,
 CONSTRAINT [PK__pet__3213E83FC83985CB] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PetCategory]    Script Date: 28-05-2024 11:03:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PetCategory](
	[id] [int] NOT NULL,
	[name] [varchar](50) NULL,
 CONSTRAINT [PK__PetCateg__3213E83F3A8F1160] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_pet_category]    Script Date: 28-05-2024 11:03:27 ******/
CREATE NONCLUSTERED INDEX [IX_pet_category] ON [dbo].[pet]
(
	[category] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[pet]  WITH CHECK ADD  CONSTRAINT [FK__pet__category__45F365D3] FOREIGN KEY([category])
REFERENCES [dbo].[PetCategory] ([id])
GO
ALTER TABLE [dbo].[pet] CHECK CONSTRAINT [FK__pet__category__45F365D3]
GO
/****** Object:  StoredProcedure [dbo].[AddPet]    Script Date: 28-05-2024 11:03:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[AddPet]
    @Name NVARCHAR(100),
    @Age INT,
    @Location NVARCHAR(100),
    @Category INT
AS
BEGIN
    INSERT INTO Pet (Name, Age, Location, Category)
    VALUES (@Name, @Age, @Location, @Category);
END;
GO
/****** Object:  StoredProcedure [dbo].[DeletePet]    Script Date: 28-05-2024 11:03:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[DeletePet]
    @Id INT
AS
BEGIN
    DELETE FROM Pet WHERE Id = @Id;
END;
GO
/****** Object:  StoredProcedure [dbo].[get_pet]    Script Date: 28-05-2024 11:03:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create  procedure [dbo].[get_pet]
as
begin
select * from pet
end
GO
/****** Object:  StoredProcedure [dbo].[GetPetById]    Script Date: 28-05-2024 11:03:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GetPetById]
    @Id INT
AS
BEGIN
    SELECT p.Id, p.Name, p.Age, p.Location, p.Category, c.Name as CategoryName
    FROM Pet p
    JOIN PetCategory c ON p.Category = c.Id
    WHERE p.Id = @Id;
END;
GO
/****** Object:  StoredProcedure [dbo].[GetPets]    Script Date: 28-05-2024 11:03:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GetPets]
AS
BEGIN
    SELECT p.Id, p.Name, p.Age, p.Location, p.Category, c.Name as CategoryName
    FROM Pet p
    JOIN PetCategory c ON p.Category = c.Id;
END;
GO
/****** Object:  StoredProcedure [dbo].[UpdatePet]    Script Date: 28-05-2024 11:03:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[UpdatePet]
    @Id INT,
    @Name NVARCHAR(100),
    @Age INT,
    @Location NVARCHAR(100),
    @Category INT
AS
BEGIN
    UPDATE Pet
    SET Name = @Name, Age = @Age, Location = @Location, Category = @Category
    WHERE Id = @Id;
END;
GO
USE [master]
GO
ALTER DATABASE [Mvc_Pet_Db] SET  READ_WRITE 
GO
